version: "3.8"
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "5432:5432"
  backend:
    build:
      context: backend
      dockerfile: .docker/Dockerfile
      target: dev
    volumes:
      - ./backend:/source
      - bin:/source/bin
      - obj:/source/obj
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOSTNAME
    command: dotnet watch run
  frontend:
    build:
      context: frontend
      dockerfile: .docker/Dockerfile
      target: prod
volumes:
  db:
  bin:
  obj: