version: "3.8"
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes: 
      - redis:/data
volumes:
  db:
  redis: