version: "3.8"
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "5432:5432"
  backend:
    build:
      context: backend
      dockerfile: .docker/Dockerfile
      target: $ENV
    volumes:
      - ./backend:/source
      - bin:/source/bin
      - obj:/source/obj
    ports:
      - "8080:8080"
    environment:
      - PGPASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOSTNAME
  frontend:
    build:
      context: frontend-vite
      dockerfile: .docker/Dockerfile
      target: $ENV
    volumes:
      - ./frontend-vite:/source
    environment:
      - FRONTEND_PORT
      - VITE_BACKEND_URL
    ports:
      - "3000:80"
volumes:
  db:
  bin:
  obj: