name: Docker Image CI

on:
  create:
    branches:    
      - main
    tags:
      - v*.*.*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the Docker image
      run: buildx build . -f ./backend/.docker/Dockerfile \
               -t blasko/fern_fuckers_app_backend:$GITHUB_REF_NAME \
               --platform linux/amd64,linux/arm64 \
               --push
