name: Docker Image for frontend

on:
  create:
    tags:
      - frontend.v.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}
    - name: Set tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: frontend
        file: frontend/.docker/Dockerfile
        platforms: linux/arm64,linux/amd64
        push: true
        tags: blasko/fern_fuckers_app_frontend:${{ steps.vars.outputs.tag  }}
