name: Docker Image for backend

on:
  create:
    branches:    
      - main
    tags:
      - v*.*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux/arm64, linux/amd64]
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}
    - name: Set tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: backend
        file: backend/.docker/Dockerfile
        platforms: ${{ matrix.arch }}
        push: true
        tags: blasko/fern_fuckers_app_backend:${{ steps.vars.outputs.tag  }}
